### ISSUE TITLE
Bug with mod stamp?

### ISSUE THREAD

**Issue by PHGaming121** [Gurge44/TOHE_PLUS#29]
![Captura de Tela (318)](https://github.com/Gurge44/TOHE_PLUS/assets/76562427/9bc7e3bd-4255-4321-b4fd-7f19e530ae77)

WHAT THE HECK IS THIS

**Comment by Gurge44** [comment]
Known
You aren't supposed to be building randomly.... Sometimes I leave some work progress in half because there's not enough time to finish it... that's why releases and text builds exist
