### ISSUE TITLE
Mod issue

### ISSUE THREAD

**Issue by NickelerLeaks** [Gurge44/TOHE_PLUS#5]
Hi.

I have an issue where whenever I start a private game up (with multiple people in lobby), it just kicks them from the server and I'm the only one that loads in, which then ends the game automatically. Also, I tried testing this in a practice round (NPC's) and I can't call button/kill without crashing (I already have the DLL in the folder)

**Comment by Gurge44** [comment]
I would need you to either send a video, or a log file that is located in Among Us/BepInEx/LogOutput.log & ErrorLog.log so I can determine the cause.

**Comment by Gurge44** [comment]
Many other people are able to host normally without issues, so this is most likely a problem on your end.
