### ISSUE TITLE
Proximity chat doesnt dissapear

### ISSUE THREAD

**Issue by PHGaming121** [Gurge44/TOHE_PLUS#7]
my suggestion is to make the message dissapear after 6 seconds, because the message never dissapear

**Comment by Gurge44** [comment]
nah it would be too easy that way

this way it took about 8 minutes to code, that way it's less than 1

**Comment by PHGaming121** [comment]
@Gurge44 u doing this?

**Comment by PHGaming121** [comment]
> nah it would be too easy that way
> 
> this way it took about 8 minutes to code, that way it's less than 1

@Gurge44 what do u mean by that?
